/** Small dependency-free LibClank operations dashboard for Worker deployments. */
export const dashboardHtml = (options: { readonly title: string; readonly apiBase?: string }): string => {
  const apiBase = options.apiBase ?? "/api"
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(options.title)}</title><style>body{font:15px system-ui,sans-serif;margin:0;background:#0b1020;color:#e5e7eb}main{max-width:960px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:baseline;border-bottom:1px solid #26324b;margin-bottom:24px}h1{margin:0 0 8px}small{color:#9ca3af}section{background:#121a2b;border:1px solid #26324b;border-radius:12px;padding:20px;margin:16px 0}article{display:grid;grid-template-columns:110px 1fr auto;gap:12px;padding:12px 0;border-bottom:1px solid #26324b}article:last-child{border:0}.status{font-weight:700;text-transform:uppercase}code{color:#93c5fd;overflow-wrap:anywhere}.completed{color:#86efac}.failed{color:#fca5a5}.running,.scheduled{color:#fcd34d}</style></head><body><main><header><div><h1>${escapeHtml(options.title)}</h1><small>LibClank workflow operations</small></div><small id="updated">Loading…</small></header><section><h2>Workflows</h2><div id="workflows">Loading…</div></section><section><h2>Recent runs</h2><div id="runs">Loading…</div></section></main><script>const api=${JSON.stringify(apiBase)},esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));async function load(){try{const[w,r]=await Promise.all([fetch(api+'/workflows').then(x=>x.json()),fetch(api+'/runs').then(x=>x.json())]);document.querySelector('#workflows').innerHTML=w.map(x=>'<article><strong>'+esc(x.id)+'</strong><code>'+esc(x.triggers.map(t=>t.path||t.id).join(', '))+'</code><span>'+esc(x.agent||'')+'</span></article>').join('')||'<small>No workflows registered.</small>';document.querySelector('#runs').innerHTML=r.map(x=>'<article><span class="status '+esc(x.status)+'">'+esc(x.status)+'</span><code>'+esc(x.runId)+'</code><small>'+new Date(x.updatedAt).toLocaleString()+'</small></article>').join('')||'<small>No runs yet.</small>';document.querySelector('#updated').textContent='Updated '+new Date().toLocaleTimeString()}catch(e){document.querySelector('#runs').textContent='Unable to load dashboard data.'}}load();setInterval(load,5000)</script></body></html>`
}

function escapeHtml(value: string): string {
  return value.replace(
    /[&<>"']/g,
    (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!,
  )
}
