/** Small dependency-free LibClank operations dashboard for Worker deployments. */
export const dashboardHtml = (options: { readonly title: string; readonly apiBase?: string }): string => {
  const apiBase = options.apiBase ?? "/api"
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(options.title)}</title><style>
:root{color-scheme:light;--ink:#111;--muted:#777;--line:#d8d8d8;--paper:#f8f8f6;--white:#fff}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 Arial,Helvetica,sans-serif}main{max-width:1080px;margin:0 auto;padding:56px 32px 96px}header{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:2px solid var(--ink);padding-bottom:16px;margin-bottom:64px}h1,h2{font-family:Georgia,"Times New Roman",serif;font-weight:400;letter-spacing:-.03em}h1{font-size:clamp(42px,7vw,76px);line-height:.95;margin:0}h2{font-size:28px;margin:0 0 24px}header small{color:var(--muted);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.08em}section{margin:0 0 64px}section>h2{border-bottom:1px solid var(--ink);padding-bottom:10px}.workflow{display:grid;grid-template-columns:minmax(220px,1fr) minmax(240px,2fr);gap:32px;padding:20px 0;border-bottom:1px solid var(--line)}.workflow-id{font-family:Georgia,"Times New Roman",serif;font-size:20px}.workflow-path{color:var(--muted);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;overflow-wrap:anywhere}.run{display:grid;grid-template-columns:100px minmax(180px,1fr) 180px;gap:24px;padding:16px 0;border-bottom:1px solid var(--line);align-items:baseline}.status{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.08em}.completed{color:#216e39}.failed{color:#a11}.running,.scheduled{color:#8a5a00}code{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;overflow-wrap:anywhere}time{color:var(--muted);font-size:12px;text-align:right}@media(max-width:640px){main{padding:32px 20px 64px}header{display:block;margin-bottom:48px}header small{display:block;margin-top:16px}.workflow,.run{display:block}.workflow-path{margin-top:8px}.run>*{display:block;margin:6px 0}time{text-align:left}}
</style></head><body><main><header><h1>${escapeHtml(options.title)}</h1><small id="updated">Loading…</small></header><section><h2>Workflows</h2><div id="workflows">Loading…</div></section><section><h2>Recent runs</h2><div id="runs">Loading…</div></section></main><script>const api=${JSON.stringify(apiBase)},esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));async function load(){try{const[w,r]=await Promise.all([fetch(api+'/workflows').then(x=>x.json()),fetch(api+'/runs').then(x=>x.json())]);document.querySelector('#workflows').innerHTML=w.map(x=>'<article class="workflow"><span class="workflow-id">'+esc(x.id)+'</span><code class="workflow-path">'+esc(x.triggers.map(t=>t.path||t.id).join(' · '))+'</code></article>').join('')||'<small>No workflows registered.</small>';document.querySelector('#runs').innerHTML=r.map(x=>'<article class="run"><span class="status '+esc(x.status)+'">'+esc(x.status)+'</span><code>'+esc(x.runId)+'</code><time>'+new Date(x.updatedAt).toLocaleString()+'</time></article>').join('')||'<small>No runs yet.</small>';document.querySelector('#updated').textContent='Updated '+new Date().toLocaleTimeString()}catch(e){document.querySelector('#runs').textContent='Unable to load dashboard data.'}}load();setInterval(load,5000)</script></body></html>`
}

function escapeHtml(value: string): string {
  return value.replace(
    /[&<>"']/g,
    (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!,
  )
}
